name: jobs examples

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step do job1
        run: echo Hello, world! job1.


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step do deploy
        run: echo Hello, world! Deploy.
