name: steps examples

on:
   push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
      - name: verification of node version
        run: node --version
  
